<a href="https://colab.research.google.com/github/harsha-9977/AIML/blob/main/ArrayTransposition%26AxisSwap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

In [23]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [25]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [27]:
np.dot(arr,arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [28]:
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [29]:
arr = np.random.randn(6,3)
arr

array([[ 1.24318986,  0.58253948,  1.00486181],
       [ 0.17404025, -0.03707336, -0.45333349],
       [ 0.77523766, -0.69576146,  0.24155679],
       [ 0.44829   ,  0.93797144, -0.37644536],
       [ 0.89882506,  0.53637855,  0.0856815 ],
       [-0.82859161, -0.11318765, -1.17264465]])

In [30]:
arr.T

array([[ 1.24318986,  0.17404025,  0.77523766,  0.44829   ,  0.89882506,
        -0.82859161],
       [ 0.58253948, -0.03707336, -0.69576146,  0.93797144,  0.53637855,
        -0.11318765],
       [ 1.00486181, -0.45333349,  0.24155679, -0.37644536,  0.0856815 ,
        -1.17264465]])

In [31]:
np.dot(arr.T,arr)

array([[3.87221893, 1.17475446, 2.23749916],
       [1.17475446, 2.0051145 , 0.25970397],
       [2.23749916, 0.25970397, 2.79775609]])

In [32]:
np.dot(arr,arr.T)

array([[ 2.89462054, -0.26076914,  0.80119027,  0.72543941,  1.51596994,
        -2.27437878],
       [-0.26076914,  0.23717569,  0.05121098,  0.21390204,  0.09770409,
         0.39158705],
       [ 0.80119027,  0.05121098,  1.14342712, -0.39600602,  0.34430846,
        -0.84686409],
       [ 0.72543941,  0.21390204, -0.39600602,  1.22246545,  0.87378764,
        -0.03617947],
       [ 1.51596994,  0.09770409,  0.34430846,  0.87378764,  1.10292975,
        -0.90594427],
       [-2.27437878,  0.39158705, -0.84686409, -0.03617947, -0.90594427,
         2.07447097]])

In [34]:
arr_1 = np.arange(12).reshape(3,4)
arr_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
arr_1.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
arr_1.transpose(0,1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
arr_1.transpose(1,0)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [41]:
arr = np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [42]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [43]:
arr.transpose(0,1,2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [44]:
arr.transpose(2,1,0)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [45]:
help(arr.swapaxes)

Help on built-in function swapaxes:

swapaxes(...) method of numpy.ndarray instance
    a.swapaxes(axis1, axis2)
    
    Return a view of the array with `axis1` and `axis2` interchanged.
    
    Refer to `numpy.swapaxes` for full documentation.
    
    See Also
    --------
    numpy.swapaxes : equivalent function



In [49]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [50]:
arr.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])