<a href="https://colab.research.google.com/github/harsha-9977/AIML/blob/main/MachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [135]:
from sklearn.datasets import load_breast_cancer

In [136]:
type(load_breast_cancer())

sklearn.utils._bunch.Bunch

In [137]:
data = load_breast_cancer()

In [138]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [139]:
import pandas as pd

In [140]:
pd.DataFrame(data.data)
# pd.DataFrame(data['data'])

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [141]:
# pd.DataFrame(data['target'])
pd.DataFrame(data.target)

,0
0,0
1,0
2,0
3,0
4,0
...,...
564,0
565,0
566,0
567,0


In [142]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [143]:
from sklearn.model_selection import train_test_split

In [144]:
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.
    
    Quick utility that wraps input validation,
    ``next(ShuffleSplit().split(X, y))``, and application to input data
    into a single call for splitting (and optionally subsampling) data into a
    one-liner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to

In [145]:
len(data.data)

569

In [146]:
569 * 0.75

426.75

In [147]:
from sklearn.model_selection import train_test_split

In [148]:
x_train, x_test, y_train, y_test = train_test_split(data.data, data.target)

In [149]:
len(x_train)

426

In [150]:
569 * 0.25

142.25

In [151]:
len(x_test)

143

In [152]:
# loading the dataset
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

data = load_breast_cancer()
x_train, x_test, y_train, y_test = train_test_split(data.data, data.target)

# Instansing the estimator and hyperparameter setting
model = DecisionTreeClassifier(criterion = 'entropy')
model

DecisionTreeClassifier(criterion='entropy')

In [153]:
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [154]:
y_pred = model.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [155]:
pred = model.predict(x_test)
pred_2d = pred.reshape(len(pred),1)
pred_2d

array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
    

In [156]:
import numpy as np

In [157]:
y_test_2d = y_test.reshape(len(pred),1)
y_test_2d

array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
    

In [158]:
df1 = pd.DataFrame(pred_2d)
df2 = pd.DataFrame(y_test_2d)

In [159]:
pd.concat([df1,df2],axis=1)

,0,0
0,0,0
1,1,1
2,1,1
3,1,1
4,1,1
...,...,...
138,1,1
139,1,1
140,1,0
141,1,1


In [160]:
df_concat = pd.concat([df1, df2],axis=1)

In [161]:
df_concat.columns = ['pred','real']

In [162]:
df_concat.columns

Index(['pred', 'real'], dtype='object')

In [163]:
df_concat[df_concat['pred'] == df_concat['real']]

,pred,real
0,0,0
1,1,1
2,1,1
3,1,1
4,1,1
...,...,...
137,1,1
138,1,1
139,1,1
141,1,1


In [164]:
len(df_concat[df_concat['pred'] == df_concat['real']])

129

In [165]:
135 / 143

0.9440559440559441

In [166]:
# Standardization

In [167]:
from sklearn.preprocessing import StandardScaler

In [168]:
scaler = StandardScaler()

In [169]:
x_train

array([[1.218e+01, 2.052e+01, 7.722e+01, ..., 7.431e-02, 2.694e-01,
        6.878e-02],
       [1.450e+01, 1.089e+01, 9.428e+01, ..., 1.221e-01, 2.889e-01,
        8.006e-02],
       [1.894e+01, 2.131e+01, 1.236e+02, ..., 1.789e-01, 2.551e-01,
        6.589e-02],
       ...,
       [1.020e+01, 1.748e+01, 6.505e+01, ..., 3.571e-02, 2.868e-01,
        7.809e-02],
       [1.916e+01, 2.660e+01, 1.262e+02, ..., 1.872e-01, 3.258e-01,
        9.720e-02],
       [9.173e+00, 1.386e+01, 5.920e+01, ..., 5.087e-02, 3.282e-01,
        8.490e-02]])

In [170]:
len(x_train)

426

In [171]:
from sklearn.preprocessing import StandardScaler

In [172]:
scaler = StandardScaler()

In [173]:
x_train

array([[1.218e+01, 2.052e+01, 7.722e+01, ..., 7.431e-02, 2.694e-01,
        6.878e-02],
       [1.450e+01, 1.089e+01, 9.428e+01, ..., 1.221e-01, 2.889e-01,
        8.006e-02],
       [1.894e+01, 2.131e+01, 1.236e+02, ..., 1.789e-01, 2.551e-01,
        6.589e-02],
       ...,
       [1.020e+01, 1.748e+01, 6.505e+01, ..., 3.571e-02, 2.868e-01,
        7.809e-02],
       [1.916e+01, 2.660e+01, 1.262e+02, ..., 1.872e-01, 3.258e-01,
        9.720e-02],
       [9.173e+00, 1.386e+01, 5.920e+01, ..., 5.087e-02, 3.282e-01,
        8.490e-02]])

In [174]:
df_scale_previous = pd.DataFrame(data.data)

In [175]:
scaler.fit(x_train)

StandardScaler()

In [176]:
x_train = scaler.transform(x_train)

In [177]:
x_train

array([[-0.52392939,  0.27122771, -0.57888366, ..., -0.58360599,
        -0.33083204, -0.84325141],
       [ 0.13544906, -1.95850083,  0.12326861, ...,  0.13509345,
        -0.02657615, -0.22864655],
       [ 1.39736299,  0.45414417,  1.33001566, ...,  0.98929156,
        -0.55395302, -1.00071666],
       ...,
       [-1.08667479, -0.43265336, -1.07977423, ..., -1.16409977,
        -0.05934217, -0.33598445],
       [ 1.45989025,  1.67898986,  1.43702597, ...,  1.11411276,
         0.54916961,  0.70524772],
       [-1.37856344, -1.27082754, -1.32054743, ..., -0.93611309,
         0.58661649,  0.03506689]])

In [178]:
df_scale_after = pd.DataFrame(x_train)

In [179]:
df_scale_previous

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [180]:
df_scale_after

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,-0.523929,0.271228,-0.578884,-0.528133,-1.191507,-1.185337,-0.793582,-0.778066,-0.248409,-0.890096,...,-0.582565,1.133307,-0.650831,-0.560628,-0.899271,-1.033052,-0.745776,-0.583606,-0.330832,-0.843251
1,0.135449,-1.958501,0.123269,-0.014199,0.956428,0.101621,0.010658,0.254322,0.155651,0.140364,...,-0.095706,-1.566887,-0.109172,-0.217579,-0.072361,-0.470461,-0.057668,0.135093,-0.026576,-0.228647
2,1.397363,0.454144,1.330016,1.367494,-0.477679,-0.027963,0.254457,0.814047,-0.790607,-1.197102,...,1.793967,0.130743,1.766718,1.726712,-0.594620,-0.128589,0.004092,0.989292,-0.553953,-1.000717
3,2.028320,0.854708,1.889762,2.141219,-0.177384,-0.040922,0.275625,0.989460,-0.144804,-1.457205,...,2.683104,1.573730,2.423726,3.026376,0.310629,0.036108,0.231678,1.320143,-0.131115,-0.490181
4,-0.083396,0.755146,0.095281,-0.190405,1.171437,2.311960,1.559370,0.833108,0.891245,1.959660,...,-0.233924,1.000379,0.069201,-0.300521,1.398668,3.233359,2.073765,1.619413,1.076546,3.206166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,0.428190,3.290507,0.510975,0.280043,0.684084,1.101272,1.089950,0.929443,0.967222,0.492853,...,0.479860,3.807876,0.589456,0.284761,2.408369,1.885211,1.470758,1.327662,0.945482,1.969329
422,0.300294,1.479866,0.276376,0.200129,0.404573,-0.124411,0.447455,0.453947,-0.566130,0.228486,...,0.483986,1.194165,0.437839,0.310789,1.437837,-0.116112,0.656700,0.593774,-0.393244,0.551597
423,-1.086675,-0.432653,-1.079774,-0.916407,-1.162123,-0.839347,-0.371353,-0.958116,0.528628,0.016709,...,-0.966276,-0.207181,-0.923742,-0.810670,-1.640444,-0.714388,-0.366465,-1.164100,-0.059342,-0.335984
424,1.459890,1.678990,1.437026,1.390084,0.375905,0.756948,1.301625,1.255284,0.314511,-0.118317,...,1.558790,1.623377,1.585372,1.480313,1.968801,0.810311,1.495560,1.114113,0.549170,0.705248


In [181]:
print(x_test)

x_test = scaler.fit_transform(x_test)

x_test

[[2.047e+01 2.067e+01 1.347e+02 ... 1.613e-01 3.220e-01 6.386e-02]
 [1.190e+01 1.465e+01 7.811e+01 ... 6.042e-02 2.727e-01 1.036e-01]
 [8.571e+00 1.310e+01 5.453e+01 ... 8.512e-02 2.983e-01 1.049e-01]
 ...
 [1.448e+01 2.146e+01 9.425e+01 ... 1.225e-01 3.020e-01 6.846e-02]
 [1.189e+01 1.835e+01 7.732e+01 ... 1.138e-01 3.397e-01 8.365e-02]
 [1.128e+01 1.339e+01 7.300e+01 ... 8.611e-02 2.102e-01 6.784e-02]]


array([[ 1.71880009,  0.36807794,  1.6881032 , ...,  0.67119115,
         0.61533982, -1.12299974],
       [-0.72267176, -1.05602801, -0.65946064, ..., -0.93113416,
        -0.2903145 ,  1.20616032],
       [-1.67105681, -1.42269981, -1.63764681, ..., -0.53881224,
         0.17996442,  1.28235327],
       ...,
       [ 0.01233376,  0.55496227,  0.01008664, ...,  0.05491218,
         0.24793442, -0.8533939 ],
       [-0.72552062, -0.18074695, -0.69223278, ..., -0.08327408,
         0.94049361,  0.03689149],
       [-0.899301  , -1.3540967 , -0.87144246, ..., -0.5230876 ,
        -1.4384564 , -0.88973208]])

In [182]:
from sklearn.datasets import load_iris

In [183]:
iris = load_iris()

In [184]:
import pandas as pd

In [185]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [186]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [187]:
iris_df = pd.DataFrame(iris.data)

In [188]:
iris_df.columns

RangeIndex(start=0, stop=4, step=1)

In [189]:
iris_df.columns = ['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width']

In [190]:
iris_df.columns

Index(['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width'], dtype='object')

In [191]:
iris_df['Sepal_Length']

,Sepal_Length
0,5.1
1,4.9
2,4.7
3,4.6
4,5.0
...,...
145,6.7
146,6.3
147,6.5
148,6.2


In [192]:
import numpy as np

In [193]:
np.mean(iris_df['Sepal_Length'])

np.float64(5.843333333333334)

In [194]:
data = [[1,2,3,4],[5,6,np.nan,8],[10,11,12,np.nan]]

In [195]:
np.array(data)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [196]:
pd.DataFrame(np.array(data), columns = ['A','B','C','D'])

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN


In [197]:
df = pd.DataFrame(np.array(data), columns = ['A','B','C','D'])
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN


In [198]:
df.isnull()

,A,B,C,D
0,False,False,False,False
1,False,False,True,False
2,False,False,False,True


In [199]:
df.isnull().sum()

,0
A,0
B,0
C,1
D,1


In [200]:
df.dropna()

,A,B,C,D
0,1.0,2.0,3.0,4.0


In [201]:
df.dropna(inplace=True)
df

,A,B,C,D
0,1.0,2.0,3.0,4.0


In [202]:
df = pd.DataFrame(np.array(data), columns=['A','B','C','D'])
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN


In [203]:
df.dropna(axis=1, inplace=True)
df

,A,B
0,1.0,2.0
1,5.0,6.0
2,10.0,11.0


In [204]:
df = pd.DataFrame(np.array(data), columns = ['A','B','C','D'])
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN


In [205]:
df.loc[3] = [np.nan,np.nan,np.nan,np.nan]
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN
3,NaN,NaN,NaN,NaN


In [206]:
df = pd.DataFrame(np.array(data), columns=['A','B','C','D'])
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN


In [207]:
new_row = pd.DataFrame(np.array([[np.nan] * 4]), columns = df.columns)
df = pd.concat([df,new_row],ignore_index=True)
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN
3,NaN,NaN,NaN,NaN


In [208]:
df.iloc[3] = [np.nan] * len(df)
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN
3,NaN,NaN,NaN,NaN


In [209]:
df.dropna(how='all', inplace=True)
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN


In [210]:
df = pd.DataFrame(np.array(data), columns=['A','B','C','D'])
df.loc[3] = [np.nan] * df.shape[1]
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN
3,NaN,NaN,NaN,NaN


In [211]:
df.dropna(thresh=3, inplace=True)
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN


In [212]:
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN


In [213]:
df.dropna(subset=['C'], inplace=True)
df

,A,B,C,D
0,1.0,2.0,3.0,4.0
2,10.0,11.0,12.0,NaN


In [214]:
from sklearn.impute import SimpleImputer

In [215]:
df = pd.DataFrame(np.array(data), columns=['A','B','C','d'])
df

,A,B,C,d
0,1.0,2.0,3.0,4.0
1,5.0,6.0,NaN,8.0
2,10.0,11.0,12.0,NaN


In [216]:
impt = SimpleImputer(missing_values=np.nan, strategy='mean')

In [217]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [218]:
help(impt.fit)

Help on method fit in module sklearn.impute._base:

fit(X, y=None) method of sklearn.impute._base.SimpleImputer instance
    Fit the imputer on `X`.
    
    Parameters
    ----------
    X : {array-like, sparse matrix}, shape (n_samples, n_features)
        Input data, where `n_samples` is the number of samples and
        `n_features` is the number of features.
    
    y : Ignored
        Not used, present here for API consistency by convention.
    
    Returns
    -------
    self : object
        Fitted estimator.



In [219]:
imputed = impt.fit(df)
imputed

SimpleImputer()

In [220]:
imputed.transform(df)

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [221]:
# Categorical Data Processing

In [222]:
df = pd.DataFrame([['green','M',10.1,'class2'],
                   ['red','L',13.5,'class1'],
                   ['blue','XL',15.3,'class2']])
df

,0,1,2,3
0,green,M,10.1,class2
1,red,L,13.5,class1
2,blue,XL,15.3,class2


In [223]:
size_mapping = {
    'XL' : 3,
    'L' : 2,
    'M' : 1
}

In [224]:
df.columns = ['color','size','price','classlabel']

In [225]:
df

,color,size,price,classlabel
0,green,M,10.1,class2
1,red,L,13.5,class1
2,blue,XL,15.3,class2


In [226]:
df['size']

,size
0,M
1,L
2,XL


In [227]:
df['size'] = df['size'].map(size_mapping)

In [228]:
df['size']

,size
0,1
1,2
2,3


In [229]:
df

,color,size,price,classlabel
0,green,1,10.1,class2
1,red,2,13.5,class1
2,blue,3,15.3,class2


In [230]:
df['classlabel']

,classlabel
0,class2
1,class1
2,class2


In [231]:
df['classlabel'].value_counts()

,count
classlabel,
class2,2
class1,1


In [232]:
np.unique(df['classlabel'])

array(['class1', 'class2'], dtype=object)

In [233]:
enumerate(np.unique(df['classlabel']))

In [234]:
for idx, val in enumerate(np.unique(df['classlabel'])):
  print(idx,val)

0 class1
1 class2


In [235]:
{label : idx for idx,label in enumerate(np.unique(df['classlabel']))}

{'class1': 0, 'class2': 1}

In [236]:
class_mapping = {label : idx for idx,label in enumerate(np.unique(df['classlabel']))}

In [237]:
df['classlabel'] = df['classlabel'].map(class_mapping)
df

,color,size,price,classlabel
0,green,1,10.1,1
1,red,2,13.5,0
2,blue,3,15.3,1


In [238]:
df = pd.DataFrame([['green','M',10.1,'class2'],
                  ['red','L',13.5,'class1'],
                  ['blue','XL',15.3,'class2']])
df.columns = ['color','size','price','classlabel']

In [239]:
df

,color,size,price,classlabel
0,green,M,10.1,class2
1,red,L,13.5,class1
2,blue,XL,15.3,class2


In [240]:
df['classlabel'] = df['classlabel'].replace({'class1' : 0, 'class2' : 1})

/tmp/ipython-input-240-2871056987.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['classlabel'] = df['classlabel'].replace({'class1' : 0, 'class2' : 1})


In [241]:
df

,color,size,price,classlabel
0,green,M,10.1,1
1,red,L,13.5,0
2,blue,XL,15.3,1


In [242]:
from sklearn.preprocessing import LabelEncoder

In [243]:
enc = LabelEncoder()

In [244]:
y = enc.fit_transform(df['classlabel'].values)

In [245]:
y

array([1, 0, 1])

In [246]:
df['classlabel'] = enc.fit_transform(df['classlabel'])

In [247]:
df

,color,size,price,classlabel
0,green,M,10.1,1
1,red,L,13.5,0
2,blue,XL,15.3,1


In [248]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [249]:
iris = pd.DataFrame(iris.target, columns=['species'])

In [250]:
iris

,species
0,0
1,0
2,0
3,0
4,0
...,...
145,2
146,2
147,2
148,2


In [251]:
iris['species'] = iris['species'].replace({0:'setosa',1:'versicolor',2:'virginica'})

In [252]:
iris

,species
0,setosa
1,setosa
2,setosa
3,setosa
4,setosa
...,...
145,virginica
146,virginica
147,virginica
148,virginica


In [253]:
pd.get_dummies(iris['species']).astype(int)

,setosa,versicolor,virginica
0,1,0,0
1,1,0,0
2,1,0,0
3,1,0,0
4,1,0,0
...,...,...,...
145,0,0,1
146,0,0,1
147,0,0,1
148,0,0,1


In [254]:
from sklearn.preprocessing import OneHotEncoder

In [255]:
onehot_encoder = OneHotEncoder()

In [256]:
len_iris = len(iris['species'])

In [257]:
len_iris

150

In [258]:
np.array(iris['species'])

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [259]:
iris_species_2d = np.array(iris['species']).reshape(len_iris,1)

In [260]:
onehot_encoder.fit_transform(iris_species_2d)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 150 stored elements and shape (150, 3)>

In [261]:
onehot_reshaped = onehot_encoder.fit_transform(iris_species_2d)

In [262]:
print(onehot_reshaped[:50])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 50 stored elements and shape (50, 3)>
  Coords	Values
  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (13, 0)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 0)	1.0
  (21, 0)	1.0
  (22, 0)	1.0
  (23, 0)	1.0
  (24, 0)	1.0
  (25, 0)	1.0
  (26, 0)	1.0
  (27, 0)	1.0
  (28, 0)	1.0
  (29, 0)	1.0
  (30, 0)	1.0
  (31, 0)	1.0
  (32, 0)	1.0
  (33, 0)	1.0
  (34, 0)	1.0
  (35, 0)	1.0
  (36, 0)	1.0
  (37, 0)	1.0
  (38, 0)	1.0
  (39, 0)	1.0
  (40, 0)	1.0
  (41, 0)	1.0
  (42, 0)	1.0
  (43, 0)	1.0
  (44, 0)	1.0
  (45, 0)	1.0
  (46, 0)	1.0
  (47, 0)	1.0
  (48, 0)	1.0
  (49, 0)	1.0


In [263]:
print(onehot_reshaped[50:100])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 50 stored elements and shape (50, 3)>
  Coords	Values
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 1)	1.0
  (6, 1)	1.0
  (7, 1)	1.0
  (8, 1)	1.0
  (9, 1)	1.0
  (10, 1)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 1)	1.0
  (14, 1)	1.0
  (15, 1)	1.0
  (16, 1)	1.0
  (17, 1)	1.0
  (18, 1)	1.0
  (19, 1)	1.0
  (20, 1)	1.0
  (21, 1)	1.0
  (22, 1)	1.0
  (23, 1)	1.0
  (24, 1)	1.0
  (25, 1)	1.0
  (26, 1)	1.0
  (27, 1)	1.0
  (28, 1)	1.0
  (29, 1)	1.0
  (30, 1)	1.0
  (31, 1)	1.0
  (32, 1)	1.0
  (33, 1)	1.0
  (34, 1)	1.0
  (35, 1)	1.0
  (36, 1)	1.0
  (37, 1)	1.0
  (38, 1)	1.0
  (39, 1)	1.0
  (40, 1)	1.0
  (41, 1)	1.0
  (42, 1)	1.0
  (43, 1)	1.0
  (44, 1)	1.0
  (45, 1)	1.0
  (46, 1)	1.0
  (47, 1)	1.0
  (48, 1)	1.0
  (49, 1)	1.0


In [264]:
print(onehot_reshaped[101:150])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 49 stored elements and shape (49, 3)>
  Coords	Values
  (0, 2)	1.0
  (1, 2)	1.0
  (2, 2)	1.0
  (3, 2)	1.0
  (4, 2)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
  (8, 2)	1.0
  (9, 2)	1.0
  (10, 2)	1.0
  (11, 2)	1.0
  (12, 2)	1.0
  (13, 2)	1.0
  (14, 2)	1.0
  (15, 2)	1.0
  (16, 2)	1.0
  (17, 2)	1.0
  (18, 2)	1.0
  (19, 2)	1.0
  (20, 2)	1.0
  (21, 2)	1.0
  (22, 2)	1.0
  (23, 2)	1.0
  (24, 2)	1.0
  (25, 2)	1.0
  (26, 2)	1.0
  (27, 2)	1.0
  (28, 2)	1.0
  (29, 2)	1.0
  (30, 2)	1.0
  (31, 2)	1.0
  (32, 2)	1.0
  (33, 2)	1.0
  (34, 2)	1.0
  (35, 2)	1.0
  (36, 2)	1.0
  (37, 2)	1.0
  (38, 2)	1.0
  (39, 2)	1.0
  (40, 2)	1.0
  (41, 2)	1.0
  (42, 2)	1.0
  (43, 2)	1.0
  (44, 2)	1.0
  (45, 2)	1.0
  (46, 2)	1.0
  (47, 2)	1.0
  (48, 2)	1.0


In [265]:
# pip install ucimlrepo

In [266]:
from ucimlrepo import fetch_ucirepo

In [267]:
wine = fetch_ucirepo(id=109)

In [268]:
wine

{'data': {'ids': None,
  'features':      Alcohol  Malicacid   Ash  Alcalinity_of_ash  Magnesium  Total_phenols  \
  0      14.23       1.71  2.43               15.6        127           2.80   
  1      13.20       1.78  2.14               11.2        100           2.65   
  2      13.16       2.36  2.67               18.6        101           2.80   
  3      14.37       1.95  2.50               16.8        113           3.85   
  4      13.24       2.59  2.87               21.0        118           2.80   
  ..       ...        ...   ...                ...        ...            ...   
  173    13.71       5.65  2.45               20.5         95           1.68   
  174    13.40       3.91  2.48               23.0        102           1.80   
  175    13.27       4.28  2.26               20.0        120           1.59   
  176    13.17       2.59  2.37               20.0        120           1.65   
  177    14.13       4.10  2.74               24.5         96           2.05   
  
  

In [269]:
wine.data.features

,Alcohol,Malicacid,Ash,Alcalinity_of_ash,Magnesium,Total_phenols,Flavanoids,Nonflavanoid_phenols,Proanthocyanins,Color_intensity,Hue,0D280_0D315_of_diluted_wines,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840


In [270]:
wine.data.targets

,class
0,1
1,1
2,1
3,1
4,1
...,...
173,3
174,3
175,3
176,3


In [271]:
np.unique(wine.data.targets)

array([1, 2, 3])

In [272]:
from sklearn.model_selection import train_test_split

In [273]:
x, y = wine.data.features, wine.data.targets

In [274]:
x

,Alcohol,Malicacid,Ash,Alcalinity_of_ash,Magnesium,Total_phenols,Flavanoids,Nonflavanoid_phenols,Proanthocyanins,Color_intensity,Hue,0D280_0D315_of_diluted_wines,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840


In [275]:
y

,class
0,1
1,1
2,1
3,1
4,1
...,...
173,3
174,3
175,3
176,3


In [276]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0, stratify=y)

In [277]:
len(x_train)

124

In [278]:
len(x_test)

54

In [279]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
x_train_norm = mms.fit_transform(x_train)
x_test_norm = mms.transform(x_test)

In [280]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
x_train_std = stdsc.fit_transform(x_train)
x_test_std = stdsc.transform(x_test)

In [281]:
from sklearn.preprocessing import RobustScaler

rbs = RobustScaler()
x_train_robust = rbs.fit_transform(x_train)
x_test_robust = rbs.transform(x_test)

In [282]:
from sklearn.preprocessing import MaxAbsScaler

mas = MaxAbsScaler()
x_train_maxabs = mas.fit_transform(x_train)
x_test_maxabs = mas.transform(x_test)