<a href="https://colab.research.google.com/github/harsha-9977/AIML/blob/main/Math_for_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [6]:
#1. Zero Vector
zero_vector = np.zeros(5)
print(zero_vector)

[0. 0. 0. 0. 0.]


In [7]:
#2. One Vector
one_vector = np.ones(5)
print(one_vector)

[1. 1. 1. 1. 1.]


In [8]:
# Square Matrix
square_matrix = np.array([[1,2],[3,4]])
print(square_matrix)

[[1 2]
 [3 4]]


In [9]:
# Diagonal Matrix
diagonal_matrix = np.diag([10,20,30])
print(diagonal_matrix)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [10]:
# Identity Matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Symmetric Matrix
Symmetric_matrix = np.array([[1,2,3],[2,5,6],[3,6,9]])
print(Symmetric_matrix)

[[1 2 3]
 [2 5 6]
 [3 6 9]]


In [25]:
# Express the vectors using Numpy

p = np.array([1_000_000,800_000,500_000])
print(p)
n = np.array([3,4,5])
print(n)

[1000000  800000  500000]
[3 4 5]


In [26]:
total_cost = np.dot(p,n)
print(total_cost)

8700000


In [27]:
# Load the mnist dataset
from sklearn.datasets import load_digits
import numpy as np

x = load_digits().data
x.shape

(1797, 64)

In [28]:
# similarity between 1st and 10th image
img1 = x[0]
img10 = x[9]

similarity = np.dot(img1,img10)
print(similarity)

2807.0


In [30]:
# similarity matrix for all image pairs
similarity_matrix = np.dot(x,x.T)
print(similarity_matrix.shape)

(1797, 1797)


In [32]:
#4
a = np.array([[2,0],[0,1]])
ainv = np.linalg.inv(a)
print(ainv)

[[0.5 0. ]
 [0.  1. ]]


In [36]:
#5 House price
# from sklearn.datasets import load_boston
# boston = load_boston()
import pandas as pd
boston = pd.read_csv("BostonHousing.csv")
boston.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2


In [38]:
boston.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [39]:
x = boston.drop('medv',axis=1).values
y = boston['medv'].values

a = x[:4,[0,4,5,6]]
b = y[:4]

In [45]:
#5
sol = np.linalg.solve(a,b,rcond=None)
sol

(array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01]),
 array([], dtype=float64),
 np.int32(4),
 array([1.28391009e+02, 2.97333579e+00, 7.58898410e-02, 7.51932881e-03]))

In [43]:
features = ['CRIM','NOX','RM',"AGE"]
for name,weight in zip(features,sol):
  print(f'{name} weight: {weight:.4f}')

CRIM weight: -312.7100
NOX weight: -115.1939
RM weight: 14.4996
AGE weight: -0.1133


In [50]:
#6
w, residuals, rank, s = np.linalg.lstsq(x,y,rcond=None)

feature_names = boston.columns
for name,weight in zip(feature_names,w):
  print(f'{name} : {weight:.4f}')

crim : -0.0929
zn : 0.0487
indus : -0.0041
chas : 2.8540
nox : -2.8684
rm : 5.9281
age : -0.0073
dis : -0.9685
rad : 0.1712
tax : -0.0094
ptratio : -0.3922
b : 0.0149
lstat : -0.4163


In [52]:
#7  vector distance
from numpy.linalg import norm
a = np.array([4,5,2,2])
b = np.array([4,0,2,0])
c = np.array([2,2,0,1])

def euclidean(u,v):
  return norm(u - v)

def cosine(u,v):
  return np.dot(u,v) / (norm(u) * norm(v))

print("Euclidean")
print(f'(a,b) : {euclidean(a,b)}')
print(f'(b,c) : {euclidean(b,c)}')
print(f'(a,c) : {euclidean(a,c)}')
print("Cosine")
print(f'(a,b) : {cosine(a,b)}')
print(f'(b,c) : {cosine(b,c)}')
print(f'(a,c) : {cosine(a,c)}')

Euclidean
(a,b) : 5.385164807134504
(b,c) : 3.605551275463989
(a,c) : 4.242640687119285
Cosine
(a,b) : 0.6388765649999398
(b,c) : 0.5962847939999439
(a,c) : 0.9523809523809523


In [53]:
#8
d = np.array([[2,1],[1,2]])
eigenValues, eigenVectors = np.linalg.eig(d)

print("Eigen Values ", eigenValues)
print("Eigen Vectos ", eigenVectors)

Eigen Values  [3. 1.]
Eigen Vectos  [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [57]:
#9
log2 = 0.69
log3 = 1.10

log12 = log3 + (2*log2)
print(log12)

2.48


In [ ]:
#10 sigmoid inverse

In [59]:
#11
#1. f(x) = x^2-1
import sympy as sp

x = sp.Symbol('x')
fx = x**3-1
result = sp.diff(fx,x)
result

3*x**2

In [64]:
#2. fx = log(x^2-3k)
x,k = sp.symbols('x k')
fx = sp.log(x**2 - 3*k)
result = sp.diff(fx,x)
result

2*x/(-3*k + x**2)

In [66]:
#3. fx = exp(ax^b)
x,a,b = sp.symbols('x a b')
fx = sp.exp(a * x**b)
result = sp.diff(fx,x)
result

a*b*x**b*exp(a*x**b)/x

In [67]:
#12 f(x,y) = exp(x^2+2y^2)
x, y = sp.symbols('x y')
f = sp.exp(x**2 + 2*y**2)


fx = sp.diff(f,x)
fy = sp.diff(f,y)
fxx = sp.diff(fx,x)
fyy = sp.diff(fy,y)
fxy = sp.diff(fx,y)
fyx = sp.diff(fy,x)

fx : 2*x*exp(x**2 + 2*y**2)
fy : 2*x*exp(x**2 + 2*y**2)
fxx : 4*x**2*exp(x**2 + 2*y**2) + 2*exp(x**2 + 2*y**2)
fxy : 8*x*y*exp(x**2 + 2*y**2)
fxy : 8*x*y*exp(x**2 + 2*y**2)
fyx : 8*x*y*exp(x**2 + 2*y**2)


In [68]:
fx

2*x*exp(x**2 + 2*y**2)

In [69]:
fy

4*y*exp(x**2 + 2*y**2)

In [70]:
fxx

4*x**2*exp(x**2 + 2*y**2) + 2*exp(x**2 + 2*y**2)

In [72]:
fxy

8*x*y*exp(x**2 + 2*y**2)

In [71]:
fyy

16*y**2*exp(x**2 + 2*y**2) + 4*exp(x**2 + 2*y**2)

In [73]:
fyx

8*x*y*exp(x**2 + 2*y**2)