<a href="https://colab.research.google.com/github/harsha-9977/AIML/blob/main/Numpy_ArrayOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

***List***

In [3]:
a = [1,2,3]

In [4]:
b = [4,5,6]

In [5]:
a+b

[1, 2, 3, 4, 5, 6]

***NumPy Arrays***

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [7]:
arr1 + arr2

array([5, 7, 9])

if the ***shape*** of the array is the same, you can perform addition, subtraction, multiplication, and division

In [8]:
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)

1
3
(3,)


In [9]:
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)

1
3
(3,)


In [10]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [11]:
# List
a = [1,2,3]
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [12]:
# NumPy
b = np.array([1,2,3])
b*3

array([3, 6, 9])

In [13]:
# NumPy repeat
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [14]:
# NumPy tile
np.tile(b,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
c = np.arange(9)

In [16]:
c = c.reshape(3,3)

In [17]:
c.shape

(3, 3)

In [18]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.tile(c,3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [20]:
np.repeat(c,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8])

In [21]:
arr2

array([4, 5, 6])

In [22]:
arr2**2

array([16, 25, 36])

In [23]:
arr1 / (arr2**2)

array([0.0625    , 0.08      , 0.08333333])

In [24]:
arr3 = np.array([10,20,30,40])
arr3

array([10, 20, 30, 40])

In [25]:
arr3 > 10

array([False,  True,  True,  True])

In [26]:
x = np.array([0,1,2,3])
x**3

array([ 0,  1,  8, 27])

In [27]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081])

---


In [28]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
x = np.arange(1,11)

In [30]:
x.sum()

np.int64(55)

In [31]:
x.mean()

np.float64(5.5)

In [32]:
x_mean = x.mean()
x-x_mean

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [33]:
(x-x_mean)**2

array([20.25, 12.25,  6.25,  2.25,  0.25,  0.25,  2.25,  6.25, 12.25,
       20.25])

In [34]:
dev = (x-x_mean)**2
dev.sum()

np.float64(82.5)

In [35]:
dev.sum() / x.size

np.float64(8.25)

In [36]:
x.var()

np.float64(8.25)

In [37]:
np.sqrt(x.var())

np.float64(2.8722813232690143)

In [38]:
np.std(x)

np.float64(2.8722813232690143)

In [39]:
x.std()

np.float64(2.8722813232690143)

In [40]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

---


In [41]:
x = np.arange(1,7)

In [42]:
x

array([1, 2, 3, 4, 5, 6])

In [43]:
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
x.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
x.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
x.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
x.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
x = x.reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
x.mean(axis=0)

array([2.5, 3.5, 4.5])

In [50]:
x.mean(axis=1)

array([2., 5.])

In [51]:
np.random.seed(123)

In [95]:
np.random.randint(10)

2

In [83]:
np.random.randint(1,11)

4

In [109]:
while True:
  num = np.random.randint(1,11)
  print(num)
  if num == 10:
    break

10


In [114]:
x = np.array([0,1,2,3,4,5])

In [116]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [117]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [119]:
np.random.seed(123)
a = np.random.randint(1,11,size=1000)
a

array([ 3,  3,  7,  2,  4, 10,  7,  2,  1,  2, 10,  1,  1, 10,  4,  5,  1,
        1,  5,  2,  8,  4,  3,  5,  8,  3,  5,  9,  1,  8, 10,  4,  5,  7,
        2,  6,  7,  3,  2,  9,  4,  6,  1,  3,  7,  3,  5,  5,  7,  4,  1,
        7,  5,  8,  7,  8,  2,  6,  8, 10,  3,  5,  9,  2,  3,  2,  2,  4,
        6, 10,  1,  9,  2,  7,  4,  4,  6, 10,  8, 10,  3,  4,  4,  4,  9,
        7, 10,  8,  7,  4, 10,  7,  7,  7,  2,  4,  5,  4,  2,  1,  6,  9,
        7,  9, 10,  2,  1,  4,  2,  4,  5,  8,  7,  2,  5,  4,  4,  8,  7,
        9,  7,  5,  5,  8,  1,  1, 10,  9,  9,  5,  9,  7,  2,  7,  9,  8,
       10,  2,  8,  2,  8, 10,  9,  8,  2,  4,  2,  9,  8,  6,  2,  3,  6,
        3,  3, 10,  4,  3,  7,  8, 10,  2,  4,  9,  4,  8, 10, 10,  4,  4,
        6,  7,  1,  9,  8,  8,  5,  5,  6,  1,  9, 10,  3,  6,  2,  6, 10,
        3,  5,  4,  1,  4,  8,  8,  3,  6,  2,  8,  6, 10,  2,  3,  9,  6,
        1, 10,  4,  4,  4,  2,  8,  7,  4,  2,  8,  3,  7,  6, 10,  9, 10,
        5,  8,  9,  6, 10

In [120]:
a.size

1000

In [121]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
np.median(a)

np.float64(5.0)

In [123]:
np.mean(a)

np.float64(5.485)

In [124]:
np.sum(a)

np.int64(5485)

In [125]:
np.cumsum(a)

array([   3,    6,   13,   15,   19,   29,   36,   38,   39,   41,   51,
         52,   53,   63,   67,   72,   73,   74,   79,   81,   89,   93,
         96,  101,  109,  112,  117,  126,  127,  135,  145,  149,  154,
        161,  163,  169,  176,  179,  181,  190,  194,  200,  201,  204,
        211,  214,  219,  224,  231,  235,  236,  243,  248,  256,  263,
        271,  273,  279,  287,  297,  300,  305,  314,  316,  319,  321,
        323,  327,  333,  343,  344,  353,  355,  362,  366,  370,  376,
        386,  394,  404,  407,  411,  415,  419,  428,  435,  445,  453,
        460,  464,  474,  481,  488,  495,  497,  501,  506,  510,  512,
        513,  519,  528,  535,  544,  554,  556,  557,  561,  563,  567,
        572,  580,  587,  589,  594,  598,  602,  610,  617,  626,  633,
        638,  643,  651,  652,  653,  663,  672,  681,  686,  695,  702,
        704,  711,  720,  728,  738,  740,  748,  750,  758,  768,  777,
        785,  787,  791,  793,  802,  810,  816,  8

In [126]:
np.round(np.var(a),2)

np.float64(8.19)

In [127]:
np.round(np.mean(a),2)

np.float64(5.48)

In [128]:
np.round(np.std(a),2)

np.float64(2.86)

In [129]:
np.max(a)

np.int64(10)

In [130]:
np.min(a)

np.int64(1)

In [131]:
z = np.random.randint(10,size=1000)

In [132]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
set(z)

{np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)}

In [134]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [135]:
a.argmax()

np.int64(4)

In [136]:
a.argmin()

np.int64(1)

In [137]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [138]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [139]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [140]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [141]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [142]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [143]:
np.linalg.det(A)

np.float64(-2.0)