<a href="https://colab.research.google.com/github/harsha-9977/AIML/blob/main/NumPy_Indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***NumPy Indexing***

In [2]:
import numpy as np

In [3]:
a = np.array([0,1,2,3])
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [4]:
a[0]

np.int64(0)

In [5]:
b[0]

array([0, 1, 2, 3])

In [6]:
b[0][1]

np.int64(1)

In [7]:
b[0,1]

np.int64(1)

In [8]:
a1 = np.array([0,10,20,30,40,50])
a1[5]

np.int64(50)

In [9]:
a1[5] = 70

In [10]:
a1

array([ 0, 10, 20, 30, 40, 70])

In [11]:
a1[[1,3,4]]

array([10, 30, 40])

In [12]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [13]:
a2[0,2]

np.int64(30)

In [14]:
a2[0][2]

np.int64(30)

In [15]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [16]:
a2[1]

array([40, 50, 60])

In [17]:
a2[2] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [40, 50, 60],
       [45, 55, 65]])

In [18]:
# [[row_position1, row_position2,....,row_positionn],[col_position1, col_position2,...., col_positionn]]
a2[[0,2],[0,1]]

array([10, 55])

In [19]:
a = np.array([1,2,3,4,5,6])

In [20]:
a[a>3]

array([4, 5, 6])

In [21]:
a[a%2==0]

array([2, 4, 6])

***NumPy Slicing***

In [22]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [23]:
b1[:3]

array([ 0, 10, 20])

In [24]:
b1[2:]

array([20, 30, 40, 50])

In [25]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [28]:
arr2d[1,:2]

array([4, 5])

In [29]:
arr2d[:2,2]

array([3, 6])

In [30]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [31]:
a = np.arange(10,100,10).reshape(3,3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [32]:
a[:2,1:]

array([[20, 30],
       [50, 60]])

In [33]:
a[2]

array([70, 80, 90])

In [34]:
a[2,:]

array([70, 80, 90])

In [35]:
a[2:,:]

array([[70, 80, 90]])

In [36]:
a[:,:2]

array([[10, 20],
       [40, 50],
       [70, 80]])

In [37]:
a[1,:2]

array([40, 50])

In [38]:
names = np.array(['Bob','Joe','Tom','Bob','Tom','Joe','Joe'])
names

array(['Bob', 'Joe', 'Tom', 'Bob', 'Tom', 'Joe', 'Joe'], dtype='<U3')

In [39]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [40]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U3')

In [41]:
np.empty((8,4))

array([[1.  , 0.  , 0.16, 1.  ],
       [1.  , 0.  , 0.  , 1.  ],
       [1.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 0.75, 1.  ]])

In [42]:
arr = np.empty((8,4))
arr

array([[1.  , 0.  , 0.16, 1.  ],
       [1.  , 0.  , 0.  , 1.  ],
       [1.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 0.75, 1.  ]])

In [43]:
for i in range(8):
  arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [44]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [45]:
arr[[-3,-5]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [46]:
arr[[0,5],[2,3]] = [10,10]

In [47]:
arr

array([[ 0.,  0., 10.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5., 10.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [50]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
arrMask = (arr2%5 == 0)
arrMask

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False])

In [53]:
arr2[arrMask]

array([ 0,  5, 10, 15])

In [54]:
arr2 > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [56]:
arrMask2 = (arr2>=10)
arrMask2

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [57]:
arr2[arrMask & arrMask2]

array([10, 15])