<a href="https://colab.research.google.com/github/harsha-9977/AIML/blob/main/Pandas_Series%26DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
pd.Series(['Male','Female','Male','Male','Female','Female','Female'])

,0
0,Male
1,Female
2,Male
3,Male
4,Female
5,Female
6,Female


In [3]:
import numpy as np

In [4]:
pd.Series(np.array(['Male','Female','Male','Male','Female','Female','Female']))

,0
0,Male
1,Female
2,Male
3,Male
4,Female
5,Female
6,Female


In [5]:
ser = pd.Series(np.array(['Male','Female','Male','Male','Female','Female','Female']))

In [6]:
type(ser)

pandas.core.series.Series

In [9]:
dict_data = {'a':1,'b':2,'c':3}

In [10]:
pd.Series(dict_data)

,0
a,1
b,2
c,3


In [11]:
ser1 = pd.Series(dict_data)
type(ser1)

pandas.core.series.Series

In [12]:
ser1.index

Index(['a', 'b', 'c'], dtype='object')

In [13]:
ser1.values

array([1, 2, 3])

In [14]:
list_data = ['2019-01-02',3.14,'ABC',100,True]

In [16]:
ser2 = pd.Series(list_data)
ser2

,0
0,2019-01-02
1,3.14
2,ABC
3,100
4,True


In [17]:
ser2.index

RangeIndex(start=0, stop=5, step=1)

In [18]:
df = {
    'Name' : ['Harris','Henry','Elizabeth'],
    'Age' : [22, 35, 58],
    'Sex' : ['male', 'male', 'female']
}
df

{'Name': ['Harris', 'Henry', 'Elizabeth'],
 'Age': [22, 35, 58],
 'Sex': ['male', 'male', 'female']}

In [21]:
data = pd.DataFrame(df)
data

,Name,Age,Sex
0,Harris,22,male
1,Henry,35,male
2,Elizabeth,58,female


In [22]:
data['Age']

,Age
0,22
1,35
2,58


In [23]:
type(data['Age'])

pandas.core.series.Series

In [24]:
data['Age'][0]

np.int64(22)

In [25]:
data = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
data

,0,1,2
0,1,2,3
1,4,5,6
2,7,8,9


In [26]:
data.columns

RangeIndex(start=0, stop=3, step=1)

In [27]:
data[0]

,0
0,1
1,4
2,7


In [28]:
type(data[0])

pandas.core.series.Series

In [31]:
dict1 = {'Brown':220,'Blue':215,'Hazel':93,'Green':64}
dict1

{'Brown': 220, 'Blue': 215, 'Hazel': 93, 'Green': 64}

In [33]:
eye = pd.Series(dict1)
eye

,0
Brown,220
Blue,215
Hazel,93
Green,64


In [34]:
eye.index

Index(['Brown', 'Blue', 'Hazel', 'Green'], dtype='object')

In [35]:
type(eye)

pandas.core.series.Series

In [36]:
eye.name

In [37]:
eye.name = 'eye_color'

In [38]:
eye

,eye_color
Brown,220
Blue,215
Hazel,93
Green,64


In [39]:
eye.name

'eye_color'

In [40]:
eye.index

Index(['Brown', 'Blue', 'Hazel', 'Green'], dtype='object')

In [41]:
eye.values

array([220, 215,  93,  64])

In [42]:
eye.sort_values()

,eye_color
Green,64
Hazel,93
Blue,215
Brown,220


In [43]:
eye.sort_index()

,eye_color
Blue,215
Brown,220
Green,64
Hazel,93


In [45]:
eye.unique()

array([220, 215,  93,  64])

In [46]:
eye.nunique()

4

In [52]:
my_data = [220,215,93,64,64]
my_data

[220, 215, 93, 64, 64]

In [53]:
eye2 = pd.Series(data = my_data, index=['Brown','Blue','Blue','Hazel','Green'])
eye2

,0
Brown,220
Blue,215
Blue,93
Hazel,64
Green,64


In [54]:
eye2.unique()

array([220, 215,  93,  64])

In [55]:
eye2.nunique()

4

In [56]:
eye2.value_counts()

,count
64,2
220,1
215,1
93,1


In [57]:
ser = pd.Series([0,10,20,30,40], index=['a','b','c','d','e'])
ser

,0
a,0
b,10
c,20
d,30
e,40


In [58]:
ser[1]

/tmp/ipython-input-58-4267038266.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser[1]


np.int64(10)

In [59]:
ser['b']

np.int64(10)

In [60]:
ser[1:3]

,0
b,10
c,20


In [61]:
ser1 = pd.Series([0,1,2,3,4], index=[0,1,2,3,4])
ser2 = pd.Series([0,1,2,3,4], index=[4,3,2,1,0])

In [62]:
ser1

,0
0,0
1,1
2,2
3,3
4,4


In [63]:
ser2

,0
4,0
3,1
2,2
1,3
0,4


In [64]:
ser1+ser2

,0
0,4
1,4
2,4
3,4
4,4


In [66]:
ser1*ser2

,0
0,0
1,3
2,4
3,3
4,0


In [67]:
ser1/ser2

,0
0,0.000000
1,0.333333
2,1.000000
3,3.000000
4,inf


In [69]:
ser1.mean()

np.float64(2.0)

In [68]:
ser1.sum()

np.int64(10)

In [70]:
ser1.median()

2.0

In [71]:
ser1.max()

4

In [72]:
ser1.min()

0

In [73]:
ser1.std()

1.5811388300841898

In [74]:
ser1.sort_values()

,0
0,0
1,1
2,2
3,3
4,4


In [76]:
ser_height = pd.Series([160,170,180],name='height')
ser_height

,height
0,160
1,170
2,180


In [79]:
plus_10 = lambda x : x+10

In [80]:
plus_10(5)

15

In [81]:
ser_height.apply(lambda x : x+10)

,height
0,170
1,180
2,190


// ***Practice***

In [88]:
from sklearn.datasets import load_iris

iris_df = load_iris()


In [95]:
iris_df.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [89]:
iris_df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [90]:
iris_df.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [93]:
iris_df.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [96]:
iris = pd.DataFrame(iris_df.data, columns = ['Sepal.Length','Sepal.Width','Petal_Length','Petal.Width'])
iris

,Sepal.Length,Sepal.Width,Petal_Length,Petal.Width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [98]:
iris['Species'] = pd.Categorical.from_codes(iris_df.target, iris_df.target_names)
iris

,Sepal.Length,Sepal.Width,Petal_Length,Petal.Width,Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [100]:
type(iris)

pandas.core.frame.DataFrame

In [101]:
data = {
    'NAME' : ['Jake','Jennifer','Paul','Andrew'],
    'AGE' : [24,21,25,19],
    'GENDER' : ['M','F','M','M']
}
pd.DataFrame(data)

,NAME,AGE,GENDER
0,Jake,24,M
1,Jennifer,21,F
2,Paul,25,M
3,Andrew,19,M


In [103]:
df = pd.DataFrame(data)
df

,NAME,AGE,GENDER
0,Jake,24,M
1,Jennifer,21,F
2,Paul,25,M
3,Andrew,19,M


In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   NAME    4 non-null      object
 1   AGE     4 non-null      int64 
 2   GENDER  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [105]:
df.head()

,NAME,AGE,GENDER
0,Jake,24,M
1,Jennifer,21,F
2,Paul,25,M
3,Andrew,19,M


In [107]:
# help(df.info)

In [110]:
from sklearn.datasets import load_iris

iris_df = load_iris()

df = pd.DataFrame(iris_df.data, columns = ['Sepal.Length','Sepal.Width','Petal.Length','Petal.Width'])
df

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [111]:
df['Species'] = pd.Categorical.from_codes(iris_df.target,iris_df.target_names)
df

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [112]:
df.head()

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [113]:
df.tail()

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica


In [114]:
df.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [115]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [117]:
df.columns = ['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width','Species']
df

,Sepal_Length,Sepal_Width,Petal_Length,Petal_Width,Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [118]:
df.Sepal_Length

,Sepal_Length
0,5.1
1,4.9
2,4.7
3,4.6
4,5.0
...,...
145,6.7
146,6.3
147,6.5
148,6.2


In [119]:
df['Sepal_Length']

,Sepal_Length
0,5.1
1,4.9
2,4.7
3,4.6
4,5.0
...,...
145,6.7
146,6.3
147,6.5
148,6.2


In [121]:
df[['Sepal_Length','Sepal_Width']]

,Sepal_Length,Sepal_Width
0,5.1,3.5
1,4.9,3.0
2,4.7,3.2
3,4.6,3.1
4,5.0,3.6
...,...,...
145,6.7,3.0
146,6.3,2.5
147,6.5,3.0
148,6.2,3.4


In [122]:
data = {
    'Name' : ['Tom','Alice'],
    'Age' : [15,10],
    'Sex' : ['Male','Female'],
    'School' : ['middle','elementary']
}
data

{'Name': ['Tom', 'Alice'],
 'Age': [15, 10],
 'Sex': ['Male', 'Female'],
 'School': ['middle', 'elementary']}

In [124]:
df = pd.DataFrame(data)
df

,Name,Age,Sex,School
0,Tom,15,Male,middle
1,Alice,10,Female,elementary


In [125]:
df = pd.DataFrame([['Name','Age','Sex','School'],['Tom',15,'Male','middle'],['Alice',10,'Female','elementary']])
df

,0,1,2,3
0,Name,Age,Sex,School
1,Tom,15,Male,middle
2,Alice,10,Female,elementary


In [126]:
df = pd.DataFrame([['Tom',15,'Male','middle'],['Alice',10,'Female','elementary']], columns=['Name','Age','Sex','School'])
df

,Name,Age,Sex,School
0,Tom,15,Male,middle
1,Alice,10,Female,elementary


In [127]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [128]:
df.index = ['stu1','stu2']
df

,Name,Age,Sex,School
stu1,Tom,15,Male,middle
stu2,Alice,10,Female,elementary


In [129]:
df.index

Index(['stu1', 'stu2'], dtype='object')

In [130]:
df.columns = ['student_name','years','sex2','school2']
df

,student_name,years,sex2,school2
stu1,Tom,15,Male,middle
stu2,Alice,10,Female,elementary


In [131]:
df.rename(index={'stu1' : 'Student1'})

,student_name,years,sex2,school2
Student1,Tom,15,Male,middle
stu2,Alice,10,Female,elementary


In [132]:
df

,student_name,years,sex2,school2
stu1,Tom,15,Male,middle
stu2,Alice,10,Female,elementary


In [133]:
df.rename(index = {'stu1' : 'Student1'}, inplace=True)

In [134]:
df

,student_name,years,sex2,school2
Student1,Tom,15,Male,middle
stu2,Alice,10,Female,elementary


In [135]:
df = df.rename(index={'stu2' : 'Student2'})

In [136]:
df

,student_name,years,sex2,school2
Student1,Tom,15,Male,middle
Student2,Alice,10,Female,elementary


In [138]:
df.rename(columns = {'student_name' : 'stu_name'}, inplace=True)

In [139]:
df

,stu_name,years,sex2,school2
Student1,Tom,15,Male,middle
Student2,Alice,10,Female,elementary


In [140]:
exam_data = {'math' : [90,80,70],
             'eng' : [98,89,95],
             'music' : [85,95,100],
             'science' : [100,90,90]}
exam_data

{'math': [90, 80, 70],
 'eng': [98, 89, 95],
 'music': [85, 95, 100],
 'science': [100, 90, 90]}

In [141]:
df = pd.DataFrame(exam_data, index=['stu1','stu2','stu3'])
df

,math,eng,music,science
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [145]:
df2 = df[:]
df2

,math,eng,music,science
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [146]:
df2.drop('stu2',inplace=True)

/tmp/ipython-input-146-875413597.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop('stu2',inplace=True)


In [147]:
df2

,math,eng,music,science
stu1,90,98,85,100
stu3,70,95,100,90


In [148]:
df

,math,eng,music,science
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [150]:
df3 = df[:]
df3

,math,eng,music,science
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [151]:
df3.drop(['stu2','stu3'], axis=0, inplace=True)
df3

/tmp/ipython-input-151-3866430820.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop(['stu2','stu3'], axis=0, inplace=True)


,math,eng,music,science
stu1,90,98,85,100


In [152]:
df

,math,eng,music,science
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [153]:
df4 = df[:]
df4

,math,eng,music,science
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [154]:
df4.drop('math',axis=1,inplace=True)
df4

/tmp/ipython-input-154-3774746247.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.drop('math',axis=1,inplace=True)


,eng,music,science
stu1,98,85,100
stu2,89,95,90
stu3,95,100,90


In [155]:
df

,math,eng,music,science
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [156]:
df5 = df[:]
df5

,math,eng,music,science
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [157]:
df5.drop(['eng','science'],axis=1,inplace=True)
df5

/tmp/ipython-input-157-3247293940.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5.drop(['eng','science'],axis=1,inplace=True)


,math,music
stu1,90,85
stu2,80,95
stu3,70,100


In [158]:
df

,math,eng,music,science
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [160]:
label1 = df.loc['stu1']
label1

,stu1
math,90
eng,98
music,85
science,100


In [161]:
position1 = df.iloc[0]
position1

,stu1
math,90
eng,98
music,85
science,100


In [162]:
label2 = df.loc[['stu1','stu2']]
label2

,math,eng,music,science
stu1,90,98,85,100
stu2,80,89,95,90


In [163]:
position2 = df.iloc[[0,1]]
position2

,math,eng,music,science
stu1,90,98,85,100
stu2,80,89,95,90


In [164]:
math1 = df['math']
math1

,math
stu1,90
stu2,80
stu3,70


In [165]:
english = df.eng
english

,eng
stu1,98
stu2,89
stu3,95


In [166]:
music_sci = df[['music','science']]
music_sci

,music,science
stu1,85,100
stu2,95,90
stu3,100,90


In [167]:
df['math']

,math
stu1,90
stu2,80
stu3,70


In [168]:
df[['math']]

,math
stu1,90
stu2,80
stu3,70


In [174]:
exam_data = {
    'name' : ['hongildong','hongeeedong','hongsamdong'],
    'math' : [90,80,70],
    'eng' : [98,89,95],
    'music' : [85,95,100],
    'phys_tra' : [100,90,90]
}
exam_data

{'name': ['hongildong', 'hongeeedong', 'hongsamdong'],
 'math': [90, 80, 70],
 'eng': [98, 89, 95],
 'music': [85, 95, 100],
 'phys_tra': [100, 90, 90]}

In [175]:
df = pd.DataFrame(exam_data)
df

,name,math,eng,music,phys_tra
0,hongildong,90,98,85,100
1,hongeeedong,80,89,95,90
2,hongsamdong,70,95,100,90


In [176]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [177]:
df.set_index('name',inplace=True)

In [178]:
df

,math,eng,music,phys_tra
name,,,,
hongildong,90,98,85,100
hongeeedong,80,89,95,90
hongsamdong,70,95,100,90


In [179]:
df.index

Index(['hongildong', 'hongeeedong', 'hongsamdong'], dtype='object', name='name')

In [180]:
a = df.loc['hongildong','music']
a

np.int64(85)

In [181]:
c = df.loc['hongildong',['music','phys_tra']]
c

,hongildong
music,85
phys_tra,100


In [182]:
d = df.iloc[0,[2,3]]
d

,hongildong
music,85
phys_tra,100


In [183]:
e = df.loc['hongildong','music':'phys_tra']
e

,hongildong
music,85
phys_tra,100


In [184]:
f = df.iloc[0,2:]
f

,hongildong
music,85
phys_tra,100


In [185]:
g = df.loc[['hongildong','hongeeedong'],['music','phys_tra']]
g

,music,phys_tra
name,,
hongildong,85,100
hongeeedong,95,90


In [186]:
h = df.iloc[[0,1],[2,3]]
h

,music,phys_tra
name,,
hongildong,85,100
hongeeedong,95,90


In [187]:
i = df.loc['hongildong':'hongeeedong', 'music':'phys_tra']
i

,music,phys_tra
name,,
hongildong,85,100
hongeeedong,95,90


In [188]:
df

,math,eng,music,phys_tra
name,,,,
hongildong,90,98,85,100
hongeeedong,80,89,95,90
hongsamdong,70,95,100,90


In [189]:
df['kor'] = 80
df

,math,eng,music,phys_tra,kor
name,,,,,
hongildong,90,98,85,100,80
hongeeedong,80,89,95,90,80
hongsamdong,70,95,100,90,80


In [190]:
df

,math,eng,music,phys_tra,kor
name,,,,,
hongildong,90,98,85,100,80
hongeeedong,80,89,95,90,80
hongsamdong,70,95,100,90,80


In [191]:
df.loc[3] = 0
df

,math,eng,music,phys_tra,kor
name,,,,,
hongildong,90,98,85,100,80
hongeeedong,80,89,95,90,80
hongsamdong,70,95,100,90,80
3,0,0,0,0,0


In [192]:
df.loc[3] = [90,80,70,60,77]
df

,math,eng,music,phys_tra,kor
name,,,,,
hongildong,90,98,85,100,80
hongeeedong,80,89,95,90,80
hongsamdong,70,95,100,90,80
3,90,80,70,60,77


In [193]:
df.index

Index(['hongildong', 'hongeeedong', 'hongsamdong', 3], dtype='object', name='name')

In [194]:
df.index[3]

3

In [195]:
df

,math,eng,music,phys_tra,kor
name,,,,,
hongildong,90,98,85,100,80
hongeeedong,80,89,95,90,80
hongsamdong,70,95,100,90,80
3,90,80,70,60,77


In [196]:
df = df.reset_index()
df

,name,math,eng,music,phys_tra,kor
0,hongildong,90,98,85,100,80
1,hongeeedong,80,89,95,90,80
2,hongsamdong,70,95,100,90,80
3,3,90,80,70,60,77


In [197]:
df.iloc[3,0] = 'hongsadong'
df

,name,math,eng,music,phys_tra,kor
0,hongildong,90,98,85,100,80
1,hongeeedong,80,89,95,90,80
2,hongsamdong,70,95,100,90,80
3,hongsadong,90,80,70,60,77


In [199]:
df.set_index('name',inplace=True)
df

,math,eng,music,phys_tra,kor
name,,,,,
hongildong,90,98,85,100,80
hongeeedong,80,89,95,90,80
hongsamdong,70,95,100,90,80
hongsadong,90,80,70,60,77


In [200]:
exam_data = {
    'name' : ['stu1','stu2','stu3'],
    'math' : [90,80,70],
    'eng' : [98,89,95],
    'mus' : [85,95,100],
    'phy' : [100,90,90]
}
df = pd.DataFrame(exam_data)
df

,name,math,eng,mus,phy
0,stu1,90,98,85,100
1,stu2,80,89,95,90
2,stu3,70,95,100,90


In [201]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [202]:
df.set_index('name',inplace=True)
df

,math,eng,mus,phy
name,,,,
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [203]:
df.iloc[0][3] = 80
df

/tmp/ipython-input-203-197081377.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.iloc[0][3] = 80
/tmp/ipython-input-203-197081377.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, i

,math,eng,mus,phy
name,,,,
stu1,90,98,85,80
stu2,80,89,95,90
stu3,70,95,100,90


In [204]:
df.loc['stu1']['phy'] = 90
df

/tmp/ipython-input-204-178165543.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.loc['stu1']['phy'] = 90


,math,eng,mus,phy
name,,,,
stu1,90,98,85,90
stu2,80,89,95,90
stu3,70,95,100,90


In [205]:
df.loc['stu1','phy'] = 100
df

,math,eng,mus,phy
name,,,,
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [208]:
df.loc['stu1',['mus','phy']] = 50
df

,math,eng,mus,phy
name,,,,
stu1,90,98,50,50
stu2,80,89,95,90
stu3,70,95,100,90


In [209]:
df.loc['stu1',['mus','phy']] = 100,150
df

,math,eng,mus,phy
name,,,,
stu1,90,98,100,150
stu2,80,89,95,90
stu3,70,95,100,90


In [210]:
df.reset_index(inplace=True)
df

,name,math,eng,mus,phy
0,stu1,90,98,100,150
1,stu2,80,89,95,90
2,stu3,70,95,100,90


In [211]:
dff = df.transpose()
dff

,0,1,2
name,stu1,stu2,stu3
math,90,80,70
eng,98,89,95
mus,100,95,100
phy,150,90,90


In [212]:
dfff = dff.T
dfff

,name,math,eng,mus,phy
0,stu1,90,98,100,150
1,stu2,80,89,95,90
2,stu3,70,95,100,90


In [213]:
exam_data = {
    'name' : ['stu1','stu2','stu3'],
    'math' : [90,80,70],
    'eng' : [98,89,95],
    'mus' : [85,95,100],
    'phy' : [100,90,90]
}
df = pd.DataFrame(exam_data)
df

,name,math,eng,mus,phy
0,stu1,90,98,85,100
1,stu2,80,89,95,90
2,stu3,70,95,100,90


In [215]:
ndf = df.set_index('name')
ndf

,math,eng,mus,phy
name,,,,
stu1,90,98,85,100
stu2,80,89,95,90
stu3,70,95,100,90


In [216]:
ndf2 = ndf.set_index('mus')
ndf2

,math,eng,phy
mus,,,
85,90,98,100
95,80,89,90
100,70,95,90


In [217]:
ndf3 = ndf.set_index(['math','mus'])
ndf3

,,eng,phy
math,mus,,
90,85,98,100
80,95,89,90
70,100,95,90


In [219]:
dict_data = {
    'c0' : [1,2,3],
    'c1' : [4,5,6],
    'c2' : [7,8,9],
    'c3' : [10,11,12],
    'c4' : [13,14,15]
}
df = pd.DataFrame(dict_data, index=['r0','r1','r2'])
df

,c0,c1,c2,c3,c4
r0,1,4,7,10,13
r1,2,5,8,11,14
r2,3,6,9,12,15


In [220]:
new_index = ['r0','r1','r2','r3','r4']
ndf = df.reindex(new_index)
ndf

,c0,c1,c2,c3,c4
r0,1.0,4.0,7.0,10.0,13.0
r1,2.0,5.0,8.0,11.0,14.0
r2,3.0,6.0,9.0,12.0,15.0
r3,NaN,NaN,NaN,NaN,NaN
r4,NaN,NaN,NaN,NaN,NaN


In [221]:
new_index = ['r0','r1','r2','r3','r4']
ndf2 = df.reindex(new_index, fill_value=0)
ndf2

,c0,c1,c2,c3,c4
r0,1,4,7,10,13
r1,2,5,8,11,14
r2,3,6,9,12,15
r3,0,0,0,0,0
r4,0,0,0,0,0


In [222]:
dict_data = {
    'c0' : [1,2,3],
    'c1' : [4,5,6],
    'c2' : [7,8,9],
    'c3' : [10,11,12],
    'c4' : [13,14,15]
}
df = pd.DataFrame(dict_data, index=['r0','r1','r2'])
df

,c0,c1,c2,c3,c4
r0,1,4,7,10,13
r1,2,5,8,11,14
r2,3,6,9,12,15


In [223]:
ndf = df.reset_index()
ndf

,index,c0,c1,c2,c3,c4
0,r0,1,4,7,10,13
1,r1,2,5,8,11,14
2,r2,3,6,9,12,15


In [224]:
df

,c0,c1,c2,c3,c4
r0,1,4,7,10,13
r1,2,5,8,11,14
r2,3,6,9,12,15


In [225]:
ndf = df.sort_index(ascending=False)
ndf

,c0,c1,c2,c3,c4
r2,3,6,9,12,15
r1,2,5,8,11,14
r0,1,4,7,10,13


In [226]:
df

,c0,c1,c2,c3,c4
r0,1,4,7,10,13
r1,2,5,8,11,14
r2,3,6,9,12,15


In [227]:
ndf = df.sort_values(by='c1',ascending=False)
ndf

,c0,c1,c2,c3,c4
r2,3,6,9,12,15
r1,2,5,8,11,14
r0,1,4,7,10,13


In [228]:
import numpy as np
import pandas as pd

In [229]:
student1 = pd.Series({
    'kor' : 100,
    'eng' : 80,
    'math' : 90
})
student1

,0
kor,100
eng,80
math,90


In [231]:
percentage = student1 / 200
percentage

,0
kor,0.50
eng,0.40
math,0.45


In [232]:
student1 = pd.Series({
    'kor' : 100,
    'eng' : 80,
    'math' : 90
})
student2 = pd.Series({
    'math' : 80,
    'kor' : 90,
    'eng' : 80
})

addition = student1 + student2
subtraction = student1 - student2
multiplication = student1 * student2
division = student1 / student2

In [233]:
result = pd.DataFrame([addition,subtraction,multiplication,division], index=['addition','subtraction','multiplication','division'])
result

,eng,kor,math
addition,160.0,190.000000,170.000
subtraction,0.0,10.000000,10.000
multiplication,6400.0,9000.000000,7200.000
division,1.0,1.111111,1.125


In [234]:
student1 = pd.Series({
    'kor' : np.nan,
    'eng' : 80,
    'math' : 90
})
student2 = pd.Series({
    'math' : 80,
    'kor' : 90
})
addition = student1 + student2
subtraction = student1 - student2
multiplication = student1 * student2
divsion = student1 / student2

In [235]:
result = pd.DataFrame([addition,subtraction,multiplication,division],index=['addition','subtraction','multiplication','division'])
result

,eng,kor,math
addition,NaN,NaN,170.000
subtraction,NaN,NaN,10.000
multiplication,NaN,NaN,7200.000
division,1.0,1.111111,1.125


In [236]:
student1 = pd.Series({
    'kor' : np.nan,
    'eng' : 80,
    'math' : 90
})
student2 = pd.Series({
    'math' : 80,
    'kor' : 90
})

sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)

In [237]:
result = pd.DataFrame([sr_add,sr_sub,sr_mul,sr_div],index = ['addition','subtraction','multiplication','division'])
result

,eng,kor,math
addition,80.0,90.0,170.000
subtraction,80.0,-90.0,10.000
multiplication,0.0,0.0,7200.000
division,inf,0.0,1.125


In [238]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [239]:
df = titanic.loc[:,['age','fare']]
df.head()

,age,fare
0,22.0,7.2500
1,38.0,71.2833
2,26.0,7.9250
3,35.0,53.1000
4,35.0,8.0500


In [240]:
addition = df + 10
addition.head()

,age,fare
0,32.0,17.2500
1,48.0,81.2833
2,36.0,17.9250
3,45.0,63.1000
4,45.0,18.0500


In [242]:
subtraction = addition - df
subtraction.tail()

,age,fare
886,10.0,10.0
887,10.0,10.0
888,NaN,10.0
889,10.0,10.0
890,10.0,10.0
